<?php

namespace FondOfSpryker\Zed\CategoryStorePageSearch\Communication;

use Spryker\Zed\CategoryPageSearch\Communication\CategoryPageSearchCommunicationFactory as SprykerCategoryPageSearchCommunicationFactory;

class CategoryStorePageSearchCommunicationFactory extends SprykerCategoryPageSearchCommunicationFactory
{
}
