<?php

namespace FondOfSpryker\Zed\CategoryStorePageSearch\Persistence;

use Spryker\Zed\CategoryPageSearch\Persistence\CategoryPageSearchQueryContainer as SprykerCategoryPageSearchQueryContainer;

class CategoryStorePageSearchQueryContainer extends SprykerCategoryPageSearchQueryContainer
{
}
