<?php

namespace FondOfSpryker\Zed\CategoryStorePageSearch\Persistence;

use Spryker\Zed\CategoryPageSearch\Persistence\CategoryPageSearchPersistenceFactory as SprykerCategoryPageSearchPersistenceFactory;

class CategoryStorePageSearchPersistenceFactory extends SprykerCategoryPageSearchPersistenceFactory
{
}
